#! /bin/sh

start() {
    echo "Loading lddmodules..."
    /usr/bin/scull_load
    /usr/bin/module_load faulty
    modprobe hello
    echo "OK"
}

stop() {
    echo "Unloading lddmodules..."
    /usr/bin/scull_unload
    /usr/bin/module_unload faulty
    rmmod hello
    echo "OK"
}

restart() {
    echo "Restarting loading lddmodules"
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
